#!/bin/sh
# MultiMarkdown convenience script
#	<http://fletcherpenney.net/multimarkdown/>
#	Fletcher T. Penney
#
# Pass arguments on to the binary to convert text to LaTeX
#

multimarkdown -b -t latex $@
